/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author quile
 */
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.json.JSONArray;
import org.json.JSONObject;
import utils.ApiCliente;
//CLASE

public class AdministrarCitas extends javax.swing.JFrame {

    /**
     * Creates new form AdministrarCitas
     */
    //CONSTRUCTOR
    public AdministrarCitas() {
        initComponents();
        setLocationRelativeTo(null);
        cargarCitas();
    }
    //METODO

    private void cargarCitas() {
        try {
            //Aquí tu programa hace una petición HTTP GET.
            String respuesta = ApiCliente.get("https://shrubs-calzone-decency.ngrok-free.dev/citas");
            //VALIDACIÓN
            if (respuesta == null || respuesta.trim().isEmpty() || respuesta.startsWith("Error")) {
                limpiarTabla();
                return;
            }
            //Convierte el texto JSON en un arreglo JSON manejable.
            JSONArray array = new JSONArray(respuesta);
            DefaultTableModel modelo = (DefaultTableModel) txtCitas.getModel();
            modelo.setRowCount(0); // Limpiamos datos viejos borra filas anteriores para eviatar duplicado

            //Recorre TODAS las citas.
            for (int i = 0; i < array.length(); i++) {
                //Obtiene una cita individual del JSON.
                JSONObject cita = array.getJSONObject(i);

                //Obtiene el id.
                int id = cita.getInt("id");
                String fecha = cita.optString("fecha", "Sin fecha");
                String estado = cita.optString("estado", "PENDIENTE");

                // Valor por defecto.
                String paciente = "Desconocido";
                //Verifica si existe usuario
                if (cita.has("usuario") && !cita.isNull("usuario")) {
                    paciente = cita.getJSONObject("usuario").optString("nombre", "Desconocido");
                }

                //Valor por defecto.
                String doctor = "No asignado";
                //Porque a veces una cita NO tiene doctor.
                if (cita.has("doctor") && !cita.isNull("doctor")) {
                    JSONObject docObj = cita.getJSONObject("doctor");
                    //Obtiene usuario del doctor
                    if (docObj.has("usuario") && !docObj.isNull("usuario")) {
                        doctor = docObj.getJSONObject("usuario").optString("nombre", "No asignado");
                    }
                }
                //AGREGAR FILA A LA TABLA
                modelo.addRow(new Object[]{id, paciente, doctor, fecha, estado});
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al cargar las citas del servidor.");
        }
    }

    //MÉTODO 
    private void limpiarTabla() {
        DefaultTableModel modelo = (DefaultTableModel) txtCitas.getModel();
        modelo.setRowCount(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPInicio = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnVolver = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtCitas = new javax.swing.JTable();
        btnFinalizada = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnConfirmar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JPInicio.setBackground(new java.awt.Color(102, 153, 255));
        JPInicio.setForeground(new java.awt.Color(51, 51, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ADMNINISTRAR CITAS");

        javax.swing.GroupLayout JPInicioLayout = new javax.swing.GroupLayout(JPInicio);
        JPInicio.setLayout(JPInicioLayout);
        JPInicioLayout.setHorizontalGroup(
            JPInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPInicioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(129, 129, 129)
                .addComponent(jLabel10)
                .addGap(31, 31, 31))
        );
        JPInicioLayout.setVerticalGroup(
            JPInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPInicioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(42, 42, 42))
        );

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));

        btnVolver.setText("VOLVER");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        txtCitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "PACIENTE", "DOCTOR", "FECHA", "ESTADO"
            }
        ));
        jScrollPane2.setViewportView(txtCitas);

        btnFinalizada.setText("FINALIZADA");
        btnFinalizada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizadaActionPerformed(evt);
            }
        });

        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnConfirmar.setText("CONFIRMAR");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 216, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(btnConfirmar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFinalizada)
                .addGap(69, 69, 69)
                .addComponent(btnCancelar)
                .addGap(33, 33, 33))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFinalizada)
                    .addComponent(btnCancelar)
                    .addComponent(btnConfirmar))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JPInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Método 
    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        MenuAdministrador menu = new MenuAdministrador();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed
    // Método
    private void btnFinalizadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizadaActionPerformed
        try {
            // Obtenemos la fila seleccionada de la tabla
            int fila = txtCitas.getSelectedRow();
            // Verificamos si el usuario seleccionó una cita
            if (fila == -1) {
                JOptionPane.showMessageDialog(this, "Por favor, seleccione una cita de la tabla.");
                return;  
            }
            // Obtenemos el ID de la cita desde la columna 0 de la tabla
            int id = Integer.parseInt(txtCitas.getValueAt(fila, 0).toString());

             // Enviamos una petición PUT al backend para cambiar el estado a FINALIZADA
            ApiCliente.put("https://shrubs-calzone-decency.ngrok-free.dev/citas/estado/" + id + "/FINALIZADA");

            JOptionPane.showMessageDialog(this, "Cita marcada como Finalizada.");
            cargarCitas();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al finalizar la cita.");
        }
    }//GEN-LAST:event_btnFinalizadaActionPerformed
    // Método
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        try {
             // Obtenemos la fila seleccionada de la tabla
            int fila = txtCitas.getSelectedRow();
             // Validamos que exista una cita seleccionada
            if (fila == -1) {
                JOptionPane.showMessageDialog(this, "Por favor, seleccione una cita de la tabla.");
                return;
            }
            // Obtenemos el ID de la cita seleccionada
            int id = Integer.parseInt(txtCitas.getValueAt(fila, 0).toString());

             // Enviamos una petición PUT para cambiar el estado de la cita a CANCELADA
            ApiCliente.put("https://shrubs-calzone-decency.ngrok-free.dev/citas/estado/" + id + "/CANCELADA");

            JOptionPane.showMessageDialog(this, "Cita Cancelada con éxito.");
            cargarCitas();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al cancelar la cita.");
        }
    }//GEN-LAST:event_btnCancelarActionPerformed
    // Método
    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        try {
            // Obtenemos la fila seleccionada de la tabla
            int fila = txtCitas.getSelectedRow();
            // Validamos que el usuario haya seleccionado una cita
            if (fila == -1) {
                JOptionPane.showMessageDialog(this, "Por favor, seleccione una cita de la tabla.");
                return;
            }
            // Obtenemos el ID de la cita seleccionada
            int id = Integer.parseInt(txtCitas.getValueAt(fila, 0).toString());

            // Enviamos petición PUT al backend para confirmar la cita
            ApiCliente.put("https://shrubs-calzone-decency.ngrok-free.dev/citas/estado/" + id + "/CONFIRMADA");

            JOptionPane.showMessageDialog(this, "¡Cita Confirmada con éxito!");
            cargarCitas(); // Recargamos la tabla para ver el cambio
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al confirmar la cita.");
        }
    }//GEN-LAST:event_btnConfirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministrarCitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministrarCitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministrarCitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministrarCitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministrarCitas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPInicio;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnFinalizada;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable txtCitas;
    // End of variables declaration//GEN-END:variables
}
