/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Jazmín
 */
import utils.ApiCliente;
import org.json.JSONArray;
import org.json.JSONObject;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import utils.CargarDatos;

public class AgendarCita extends javax.swing.JFrame {

    private int usuarioIdGlobal;
    private String correoPacienteGlobal = "";

    /**
     * Creates new form AgendarCita
     */
    public AgendarCita() {
        initComponents();
    }

    // Constructor con Parámetro (El que usa tu MenuPaciente)
// Constructor con Parámetro
// Constructor con Parámetro (El que usa tu MenuPaciente)
    public AgendarCita(String correoPaciente) {
        initComponents();
        this.correoPacienteGlobal = correoPaciente;
        lblPaciente.setText(correoPaciente);

        // =========================
        // CARGAR SINTOMAS
        // =========================
        CargarDatos.cargarSintomas(cbSintoma);

        // =========================
        // CARGAR ESPECIALIDADES
        // =========================
        CargarDatos.cargarEspecialidades(cbEspecialidad);

        // =========================
        // SELECCIONAR PRIMERA
        // =========================
        if (cbEspecialidad.getItemCount() > 0) {

            cbEspecialidad.setSelectedIndex(0);

            // FORZAR CARGA
            CargarDatos.cargarDoctoresPorEspecialidad(
                    cbEspecialidad,
                    cbDoctor
            );
            // 1. Limpiamos los ítems manuales que se pusieron en el diseño
            cbFecha.removeAllItems();

            // 2. Obtenemos la fecha de hoy usando la API de Java 8+
            java.time.LocalDate hoy = java.time.LocalDate.now();

            // 3. Agregamos de forma automática el día de hoy y los siguientes 3 días
            for (int i = 0; i < 4; i++) {
                cbFecha.addItem(hoy.plusDays(i).toString());
            }
        }

        // =========================
        // HORAS
        // =========================
        CargarDatos.cargarHorasDisponibles(
                cbDoctor,
                cbFecha,
                cbHora
        );

        // =========================
        // EVENTO ESPECIALIDAD
        // =========================
        cbEspecialidad.addActionListener(
                new java.awt.event.ActionListener() {

            public void actionPerformed(
                    java.awt.event.ActionEvent evt
            ) {

                CargarDatos.cargarDoctoresPorEspecialidad(
                        cbEspecialidad,
                        cbDoctor
                );

                CargarDatos.cargarHorasDisponibles(
                        cbDoctor,
                        cbFecha,
                        cbHora
                );
            }
        });

        // =========================
        // EVENTO DOCTOR
        // =========================
        cbDoctor.addActionListener(
                new java.awt.event.ActionListener() {

            public void actionPerformed(
                    java.awt.event.ActionEvent evt
            ) {

                CargarDatos.cargarHorasDisponibles(
                        cbDoctor,
                        cbFecha,
                        cbHora
                );
            }
        });

        // =========================
        // EVENTO FECHA
        // =========================
        cbFecha.addActionListener(
                new java.awt.event.ActionListener() {

            public void actionPerformed(
                    java.awt.event.ActionEvent evt
            ) {

                CargarDatos.cargarHorasDisponibles(
                        cbDoctor,
                        cbFecha,
                        cbHora
                );
            }
        });
        CargarDatos.cargarHorasDisponibles(cbDoctor, cbFecha, cbHora);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPInicio = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblPaciente = new javax.swing.JLabel();
        cbEspecialidad = new javax.swing.JComboBox<>();
        cbDoctor = new javax.swing.JComboBox<>();
        cbFecha = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cbHora = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        btnAgendarCita = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        cbSintoma = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JPInicio.setBackground(new java.awt.Color(51, 51, 255));
        JPInicio.setForeground(new java.awt.Color(51, 51, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("AGENDAR CITA");

        javax.swing.GroupLayout JPInicioLayout = new javax.swing.GroupLayout(JPInicio);
        JPInicio.setLayout(JPInicioLayout);
        JPInicioLayout.setHorizontalGroup(
            JPInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPInicioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );
        JPInicioLayout.setVerticalGroup(
            JPInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPInicioLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLabel2.setText("Paciente:");

        jLabel3.setText("Especialidad:");

        jLabel4.setText("Doctor:");

        jLabel5.setText("Fecha:");

        lblPaciente.setText("nombre");

        cbEspecialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEspecialidadActionPerformed(evt);
            }
        });

        jLabel7.setText("Hora:");

        jLabel8.setText("Sintoma:");

        btnAgendarCita.setText("AGENDAR CITA");
        btnAgendarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgendarCitaActionPerformed(evt);
            }
        });

        btnVolver.setText("VOLVER");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        cbSintoma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbHora, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lblPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbEspecialidad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbDoctor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbFecha, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbSintoma, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(btnAgendarCita)
                .addGap(18, 18, 18)
                .addComponent(btnVolver)
                .addContainerGap(104, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addComponent(lblPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(cbEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cbSintoma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 174, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgendarCita)
                    .addComponent(btnVolver))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JPInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgendarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgendarCitaActionPerformed
     try {
            if (cbDoctor.getSelectedItem() == null || cbSintoma.getSelectedItem() == null) {
                JOptionPane.showMessageDialog(this,"Selecciona doctor y síntoma");
                return;
            }
            // =========================
            // HORA
            // =========================
            String hora
                    = cbHora.getSelectedItem().toString();

            if (hora.length() == 7) {
                hora = "0" + hora;
            }

            String fecha
                    = cbFecha.getSelectedItem().toString()
                    + "T"
                    + hora;

            // =========================
            // OBTENER PACIENTE REAL
            // =========================
            String respuestaUsuario = ApiCliente.get("https://shrubs-calzone-decency.ngrok-free.dev/usuarios/correo/"+ correoPacienteGlobal);

            JSONObject usuarioJson
                    = new JSONObject(respuestaUsuario);

            int idUsuario
                    = usuarioJson.getInt("id");

            // =========================
            // OBTENER DOCTOR
            // =========================
            String docSel
                    = cbDoctor.getSelectedItem().toString();

            int idDoctor
                    = Integer.parseInt(
                            docSel.split(" - ")[0]
                    );

            // =========================
            // OBTENER SINTOMA
            // =========================
            String seleccionado
                    = cbSintoma.getSelectedItem().toString();

            int idSintoma
                    = Integer.parseInt(
                            seleccionado.split(" - ")[0]
                    );

            // =========================
            // JSON CITA
            // =========================
            String json = "{"
                    + "\"fecha\":\"" + fecha + "\","
                    + "\"usuario\":{\"id\":" + idUsuario + "},"
                    + "\"doctor\":{\"id\":" + idDoctor + "},"
                    + "\"sintoma\":{\"id\":" + idSintoma + "}"
                    + "}";

            // =========================
            // GUARDAR CITA
            // =========================
            String respuesta
                    = ApiCliente.post(
                            "https://shrubs-calzone-decency.ngrok-free.dev/citas",
                            json
                    );

            System.out.println(respuesta);

            // ========================================================
            // 🌟 NOTIFICACIONES AUTOMÁTICAS REPARADAS
            // ========================================================
            JSONObject citaCreadaJson = new JSONObject(respuesta);
            int idCitaRecienCreada = citaCreadaJson.getInt("id");
            String fechaNotif = java.time.LocalDateTime.now().toString();

            // --- NOTIFICACIÓN 1: Al Paciente ---
            String jsonNotifPaciente = "{"
                    + "\"fecha\":\"" + fechaNotif + "\","
                    + "\"mensaje\":\"Tu cita médica ha sido agendada con éxito.\","
                    + "\"cita\":{\"id\":" + idCitaRecienCreada + "},"
                    + "\"usuario\":{\"id\":" + idUsuario + "}"
                    + "}";
            ApiCliente.post("https://shrubs-calzone-decency.ngrok-free.dev/notificaciones", jsonNotifPaciente);

            // --- NOTIFICACIÓN 2: Al Doctor asignado (CORREGIDO CON EL ID DE USUARIO REAL) ---
            // Traducimos el idDoctor (ej: 8) al usuario_id real del Login (ej: 18)
            int idUsuarioRealDelDoctor = obtenerUsuarioIdDelDoctor(idDoctor);

            String jsonNotifDoctor = "{"
                    + "\"fecha\":\"" + fechaNotif + "\","
                    + "\"mensaje\":\"Tienes una nueva cita asignada con el paciente: " + correoPacienteGlobal + "\","
                    + "\"cita\":{\"id\":" + idCitaRecienCreada + "},"
                    + "\"usuario\":{\"id\":" + idUsuarioRealDelDoctor + "}" // 🥼 ¡Ahora sí apunta a su cuenta!
                    + "}";
            ApiCliente.post("https://shrubs-calzone-decency.ngrok-free.dev/notificaciones", jsonNotifDoctor);

            // --- NOTIFICACIÓN 3: Al Administrador ---
            int idAdministrador = 1;
            String jsonNotifAdmin = "{"
                    + "\"fecha\":\"" + fechaNotif + "\","
                    + "\"mensaje\":\"Alerta de Sistema: Nueva cita registrada (ID Cita: " + idCitaRecienCreada + ")\","
                    + "\"cita\":{\"id\":" + idCitaRecienCreada + "},"
                    + "\"usuario\":{\"id\":" + idAdministrador + "}"
                    + "}";
            ApiCliente.post("https://shrubs-calzone-decency.ngrok-free.dev/notificaciones", jsonNotifAdmin);
            // ========================================================

            JOptionPane.showMessageDialog(
                    this,
                    "Cita agendada correctamente"
            );

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(
                    this,
                    "Error al agendar cita"
            );
        }
    }//GEN-LAST:event_btnAgendarCitaActionPerformed

    // MÉTODO AUXILIAR PARA TRADUCIR ID_DOCTOR A ID_USUARIO
    private int obtenerUsuarioIdDelDoctor(int doctorId) {
        if (doctorId == 8) return 18; // Samira
        if (doctorId == 5) return 14; // Maria
        if (doctorId == 6) return 15; // David
        if (doctorId == 7) return 16; // Anna
        if (doctorId == 2) return 11; // Danna
        
        return 1; // Retorno de seguridad (admin)
    }
    
    private void cbEspecialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEspecialidadActionPerformed
CargarDatos.cargarDoctoresPorEspecialidad(
                cbEspecialidad,
                cbDoctor
        );

        CargarDatos.cargarHorasDisponibles(
                cbDoctor,
                cbFecha,
                cbHora
        );
    }//GEN-LAST:event_cbEspecialidadActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
MenuPaciente menu = new MenuPaciente(usuarioIdGlobal, correoPacienteGlobal);
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgendarCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgendarCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgendarCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgendarCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgendarCita().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPInicio;
    private javax.swing.JButton btnAgendarCita;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cbDoctor;
    private javax.swing.JComboBox<String> cbEspecialidad;
    private javax.swing.JComboBox<String> cbFecha;
    private javax.swing.JComboBox<String> cbHora;
    private javax.swing.JComboBox<String> cbSintoma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblPaciente;
    // End of variables declaration//GEN-END:variables
}
