
import org.json.JSONArray;
import org.json.JSONObject;
import utils.ApiCliente;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Jazmín
 */
public class Notificaciones extends javax.swing.JFrame {

    private int usuarioIdGlobal;
    private String correoPacienteGlobal;
    private String rolGlobal = "PACIENTE";
    private String correoDoctorGlobal;

    /**
     * Creates new form NotificacionesPaciente
     */
    public Notificaciones() {
        initComponents();
    }

    public Notificaciones(int usuarioId, String correo) {
        initComponents();
        this.usuarioIdGlobal = usuarioId;
        this.correoPacienteGlobal = correo;
        this.rolGlobal = "PACIENTE";

        cargarNotificaciones();
    }

    public Notificaciones(int usuarioId, String correo, String rol) {
        initComponents();
        this.usuarioIdGlobal = usuarioId;
        this.correoPacienteGlobal = correo;
        this.rolGlobal = rol.toUpperCase(); // Guarda "PACIENTE", "DOCTOR" o "ADMIN"

        cargarNotificaciones();
    }

    // 🌐 MÉTODO ÚNICO CORREGIDO PARA EVITAR DUPLICIDAD
    private void cargarNotificaciones() {
        try {
            System.out.println("Sincronizando notificaciones para Usuario ID: " + usuarioIdGlobal);

            // 1. Limpiar el JTextArea
            txNotificaciones.setText("");

            // 2. Control por si el ID viaja en 0 (Sesión inválida)
            if (usuarioIdGlobal == 0) {
                txNotificaciones.setText("⚠️ Error: Sesión de usuario no identificada.");
                return;
            }

            // 3. Llamada al Backend
            String url = "https://shrubs-calzone-decency.ngrok-free.dev/notificaciones/usuario/" + usuarioIdGlobal;
            String respuesta = ApiCliente.get(url);

            System.out.println("RESPUESTA DESDE EL SERVIDOR: " + respuesta);

            JSONArray array = new JSONArray(respuesta);

            // 4. Si la respuesta viene vacía
            if (array.length() == 0) {
                txNotificaciones.setText("🔔 No tienes notificaciones recientes por el momento.");
                return;
            }

            // 5. Recorrer y pintar los datos exactos de la Base de Datos
            for (int i = 0; i < array.length(); i++) {
                JSONObject obj = array.getJSONObject(i);

                String fecha = obj.getString("fecha").replace("T", " ");
                String mensaje = obj.getString("mensaje"); // Muestra el texto real guardado en la BD

                txNotificaciones.append("📅 " + fecha + "\n");
                txNotificaciones.append("🔔 " + mensaje + "\n");
                txNotificaciones.append("-----------------------------------------------------------------------\n");
            }

        } catch (Exception e) {
            e.printStackTrace();
            txNotificaciones.setText("❌ Error al conectar con el servidor de notificaciones.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPInicio = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txNotificaciones = new javax.swing.JTextArea();
        btnActualizar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JPInicio.setBackground(new java.awt.Color(51, 51, 255));
        JPInicio.setForeground(new java.awt.Color(51, 51, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NOTIFICACIONES");

        javax.swing.GroupLayout JPInicioLayout = new javax.swing.GroupLayout(JPInicio);
        JPInicio.setLayout(JPInicioLayout);
        JPInicioLayout.setHorizontalGroup(
            JPInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPInicioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(142, 142, 142))
        );
        JPInicioLayout.setVerticalGroup(
            JPInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPInicioLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        txNotificaciones.setColumns(20);
        txNotificaciones.setRows(5);
        jScrollPane1.setViewportView(txNotificaciones);

        btnActualizar.setText("ACTUALIZAR");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnVolver.setText("VOLVER");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("- Tus notificaciones recientes ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addGap(0, 92, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(btnActualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVolver)
                .addGap(92, 92, 92))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar)
                    .addComponent(btnVolver))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JPInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        cargarNotificaciones(); // Llama al método principal optimizado
        javax.swing.JOptionPane.showMessageDialog(this, "Notificaciones sincronizadas con éxito.", "Actualizado", javax.swing.JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // 1. Evaluamos qué rol abrió esta ventana para regresar al menú correspondiente con sus datos intactos
        if (this.rolGlobal != null) {
            switch (this.rolGlobal.toUpperCase()) {
                case "ADMIN":
                    MenuAdministrador menuAdmin = new MenuAdministrador(this.usuarioIdGlobal, this.correoPacienteGlobal);
                    menuAdmin.setVisible(true);
                    menuAdmin.setLocationRelativeTo(null);
                    break;

                case "PACIENTE":
                    // 🔑 CORREGIDO: Le pasamos de vuelta sus credenciales al menú del paciente
                    MenuPaciente menuPaciente = new MenuPaciente(this.usuarioIdGlobal, this.correoPacienteGlobal);
                    menuPaciente.setVisible(true);
                    menuPaciente.setLocationRelativeTo(null);
                    break;

                case "DOCTOR":
                    // 🔑 CORREGIDO: Le devolvemos el ID y el correo al MenuDoctor para que no se vacíe
                    MenuDoctor menuDoc = new MenuDoctor(this.usuarioIdGlobal, this.correoPacienteGlobal);
                    menuDoc.setVisible(true);
                    menuDoc.setLocationRelativeTo(null);
                    break;

                default:
                    MenuPrincipal login = new MenuPrincipal();
                    login.setVisible(true);
                    login.setLocationRelativeTo(null);
                    break;
            }
        } else {
            MenuPrincipal login = new MenuPrincipal();
            login.setVisible(true);
            login.setLocationRelativeTo(null);
        }

        // 2. Cierra la ventana de notificaciones sin tumbar la aplicación
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Notificaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Notificaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Notificaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Notificaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Notificaciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPInicio;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txNotificaciones;
    // End of variables declaration//GEN-END:variables
}
